### ISSUE TITLE
ROS2 Foxy Support

### ISSUE THREAD

**Issue by vinnnyr** [naoki-mizuno/ds4_driver#13]
Hello,
I am interested in developing a ROS2 / Foxy support version of this driver. I am in progress doing so, and I was wondering if there is interest in holding it here in a branch called foxy-devel or is it preferred that I keep the changes in another fork since there may be significant changes?

**Comment by naoki-mizuno** [comment]
ROS2 support has been on my to-do list for quite a while now but I haven't
had the time to work on it yet. I'd be happy to merge the changes into
foxy-devel like you suggested!
