### ISSUE TITLE
controller fails to reconnect after accidental disconnect due to faulty use of rclpy.spin, wrong usage of rclpy.shutdown_now(), wrong approach ot destroying the one-shot timer in controller_ros.py

### ISSUE THREAD

**Issue by geoporus1** [naoki-mizuno/ds4_driver#20]
Hello @naoki-mizuno! After we successfully merged the latest changes to the `foxy-devel` branch I have continued working with the `ds4_driver` and spotted some more issues:
* in `ds4_driver_node.py` there is an incorrect usage of `rclpy.shutdown_now()`, a function which I have been unable to find in the current `rclpy` documentation. Needs to be replaced with `rclpy.shutdown()`
* the way in which spinning is handled now in `ds4_driver_node.py` renders the controller to be unable to reconnect if it is disconnected at some point at runtime.
* the way in which i have tried to destroy the one-shot timer reference in `controller_ros.py` was not correct previously and needs to be updated to the correct one.

I have opened a new pull request #19 for the `foxy-devel` branch in which I am addressing all of these issues with proper fixes which I have also tested thoroughly. Please check the new changes whenever you got the time and let me know if you think they are suitable.

**Comment by naoki-mizuno** [comment]
Merged #19. Thanks!
