### ISSUE TITLE
udev/50-ds4drv.rules': No such file or directory

### ISSUE THREAD

**Issue by Benedixx** [naoki-mizuno/ds4_driver#30]
hi i tried to install ds4 driver but there is a error when i tried to copy .rules file.
![Screenshot from 2022-08-26 15-46-32](https://user-images.githubusercontent.com/97221880/186869512-6096446d-9989-4417-a222-b6f349f6539a.png)
what seems the problem here? thanks

**Comment by geoporus-karelics** [comment]
The `ds4_driver` ROS package depends on the underlying `ds4drv` driver package. You need that first before trying to install this one, as specified in the very first lines of the README. 
![image](https://user-images.githubusercontent.com/67265034/186893114-af395247-656a-44eb-943a-79ba86e25cb6.png)

**Comment by naoki-mizuno** [comment]
Yup, that's right. `.rules` file is in `ds4drv`. Thanks, @geoporus-karelics!
