### ISSUE TITLE
Installation instructions does not work

### ISSUE THREAD

**Issue by MithunKinarullathil** [naoki-mizuno/ds4_driver#31]
In line 5, the copying of udev rules, there is no directory called udev in the repository. 

https://github.com/naoki-mizuno/ds4_driver/tree/noetic-devel#installation-and-usage

**Comment by naoki-mizuno** [comment]
`udev` directory is in the ds4drv repo. Have a look [here](https://github.com/naoki-mizuno/ds4drv/blob/devel/udev/50-ds4drv.rules).
