### ISSUE TITLE
Installation guide fix

### ISSUE THREAD

**Issue by florianspy** [naoki-mizuno/ds4_driver#8]
The guide give on below of Installation and Usage needs to minor fixes
after the cd ds4drv
mkdir ~/.local/lib/python2.7/site-packages
or else you get errors that this path does not exist
and before the line 
sudo cp 50-ds4drv.rules /etc/udev/rules.d/
the command
cd udev

**Comment by naoki-mizuno** [comment]
Thanks for reporting!
