### ISSUE TITLE
Causes Screen to Rotate 180

### ISSUE THREAD

**Issue by amackeith** [naoki-mizuno/ds4_driver#9]
When I boot my computer (Macbook running Ubuntu 18) with the PS4 controller plugged in the USB after the boot loader finishes the screen output is rotated 180 degrees. This did not happen before and only occurs when the PS4 controller is plugged in during boot. It works okay if I plug it in after boot though.

Replicated it on an older Macbook running Ubuntu 18 as well.

**Comment by naoki-mizuno** [comment]
I've never had this issue, but have you tried [this](https://askubuntu.com/questions/967424/using-a-ps4-controller-inverts-the-screen-17-10)?

If your DualShock 4 works normally plugging it in after boot, I suspect it's a problem related to `ds4_driver`. If you think it is indeed `ds4_driver` that is causing the screen to rotate, feel free to reopen this issue!
